name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run action in"
        required: true
        type: string
        default: "DEV"
      application:
        description: "Name of application"
        required: true
        type: string
        default: "Krish"
env:
  envi: "${{ github.event.inputs.environment }}_${{ github.event.inputs.environment }}"
  
jobs:
  first:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print environment
        run: |
          echo ${{ envi }}
          echo ${{ inputs.application }}
          #echo all env variables
          env
          # Echo variables value from env variable WSL_DISTRO_NAME
          echo $WSL_DISTRO_NAME
