name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run action in"
        required: true
        type: string
        default: "DEV"
      application:
        description: "Name of application"
        required: true
        type: string
        default: "Krish"

jobs:
  first:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.application }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print environment
        run: |
          echo ${{ inputs.environment }}
          echo ${{ inputs.application }}
          echo ${{ inputs.logLevel }}
