name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run action in"
        required: true
        type: string
        default: "DEV"
      application:
        description: "Name of application"
        required: true
        type: string
        default: "Krish"
env:
  envi: "${{ github.event.inputs.application }}_${{ github.event.inputs.environment }}"
  
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print environment
        run: |
          echo "$envi"
          echo ${{ inputs.application }}
      - name: create env
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequests = await github.rest.repos.createOrUpdateEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: ${{ github.event.inputs.application }}
            })
      
