name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run action in"
        required: true
        type: string
        default: "DEV"
      application:
        description: "Name of application"
        required: true
        type: string
        default: "Krish"
env:
  envi: "${{ github.event.inputs.application }}_${{ github.event.inputs.environment }}"
  
jobs:
  first:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print environment
        run: |
          echo $envi
          echo ${{ github.event.inputs.application }}
      - name: test
        shell: python
        run: |
          import requests
        

          headers = {
              'Accept': 'application/vnd.github+json',
              'Authorization': 'Bearer ${{ secrets.PAT }}',
              'X-GitHub-Api-Version': '2022-11-28'
          }
          repo = "django-demo"
          owner = "krishpy3"
          response = requests.put(f'https://api.github.com/repos/{owner}/{repo}/environments/dev3', headers=headers)
          print(response.json())
          
#       - name: Create environment
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const result = await github.rest.repos.createOrUpdateEnvironment({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               environment_name: "${{ github.event.inputs.environment }}",
#               deployment_branch_policy: {
#                 protected_branches: true,
#                 custom_branch_policies: false
#               }
#             })
#             console.log(result.data)
